backend:
  name: github
  repo: MouMou92/moumou92.github.io
  branch: main
  base_url: https://decap-oauth.netlify.app
  auth_endpoint: auth

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  # ACTUALITÉS : on utilise 1 fichier JSON unique qui contient une liste "items"
  - name: "actualites"
    label: "Actualités"
    files:
      - name: "news"
        label: "Liste des actualités"
        file: "content/actualites/news.json"
        format: "json"
        fields:
          - label: "Actualités"
            name: "items"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "Titre",   name: "title",   widget: "string" }
              - { label: "Slug",    name: "slug",    widget: "string", hint: "ex: fetes-communautaires-2025" }
              - { label: "Date",    name: "date",    widget: "datetime" }
              - { label: "Image",   name: "image",   widget: "image" }
              - { label: "Résumé",  name: "excerpt", widget: "text" }
              - { label: "Contenu", name: "body",    widget: "markdown" }

  # GALERIE : simple liste d’images + titre
  - name: "galerie"
    label: "Galerie photos"
    files:
      - name: "gallery"
        label: "Images de la galerie"
        file: "content/actualites/gallery.json"
        format: "json"
        fields:
          - label: "Images"
            name: "items"
            widget: "list"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
