backend:
  name: github
  repo: MouMou92/moumou92.github.io
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
